blank_issues_enabled: false
contact_links:
  - name: 讨论 / Discussions
    url: https://github.com/odomu/aliyunpan/discussions
    about: Please ask and answer questions here.
  - name: 常见问题 / Wiki
    url: https://github.com/odomu/aliyunpan/wiki
    about: Read wiki if your are new here.